INSERT OR IGNORE INTO states (abbreviation, name) VALUES
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DC', 'District of Columbia'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('INT', 'International'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming');

INSERT OR IGNORE INTO positions (name, abbr) VALUES
    ('Quarterback', 'QB'),
    ('Half Back', 'HB'),
    ('Fullback', 'FB'),
    ('Wide Receiver', 'WR'),
    ('Tight End', 'TE'),
    ('Offensive Tackle', 'OT'),
    ('Offensive Guard', 'OG'),
    ('Center', 'C'),
    ('Edge Rusher', 'EDGE'),
    ('Defensive Tackle', 'DT'),
    ('Linebacker', 'LB'),
    ('Cornerback', 'CB'),
    ('Safety', 'S'),
    ('Kicker', 'K'),
    ('Punter', 'P');

INSERT OR IGNORE INTO depth_chart_positions (name, abbr) VALUES 
    ('Quarterback', 'QB'),
    ('Half Back', 'HB'),
    ('Fullback', 'FB'),
    ('Wide Receiver', 'WR'),
    ('Tight End', 'TE'),
    ('Left Tackle', 'LT'),
    ('Left Guard', 'LG'),
    ('Center', 'C'),
    ('Right Guard', 'RG'),
    ('Right Tackle', 'RT'),
    ('Left Edge Rusher', 'LEDGE'),
    ('Right Edge Rusher', 'REDGE'),
    ('Defensive Tackle', 'DT'),
    ('Strongside Linebacker', 'SAM'),
    ('Middle Linebacker', 'MIKE'),
    ('Weakside Linebacker', 'WILL'),
    ('Corner Back', 'CB'),
    ('Free Safety', 'FS'),
    ('Strong Safety', 'SS'),
    ('Kicker', 'K'),
    ('Punter', 'P'),
    ('Punt Returner', 'PR'),
    ('Kick Returner', 'KR'),
    ('Kicker on Special Teams', 'KOS'),
    ('3rd Down Running Back', '3DRB'),
    ('Gadget Player', 'GAD'),
    ('Power Half Back', 'PWHB'),
    ('Slot Receiver', 'SLWR'),
    ('Rush Left Edge', 'RLE'),
    ('Rush Right Edge', 'RRE'),
    ('Rush Defensive Tackle', 'RDT'),
    ('Nose Tackle', 'NT'),
    ('Sub Linebacker', 'SUBLB'),
    ('Slot Corner', 'SLCB');

INSERT OR IGNORE INTO CONFERENCES (name, abbreviation) VALUES
    ('American Athletic Conference', 'AAC'),
    ('Atlantic Coast Conference', 'ACC'),
    ('Big Ten Conference', 'B10'),
    ('Big 12 Conference', 'B12'),
    ('Conference USA', 'CUSA'),
    ('FBS Independents', 'IND'),
    ('Mid-American Conference', 'MAC'),
    ('Mountain West Conference', 'MWC'),
    ('Pac-12 Conference', 'P12'),
    ('Southeastern Conference', 'SEC'),
    ('Sun Belt Conference', 'SBC');

INSERT OR IGNORE INTO divisions (name, conference_id) VALUES
    (NULL, 1),
    (NULL, 2),
    (NULL, 3),
    (NULL, 4),
    (NULL, 5),
    (NULL, 6),
    (NULL, 7),
    (NULL, 8),
    (NULL, 9),
    (NULL, 10),
    ('East', 11),
    ('West', 11);


INSERT OR IGNORE INTO locations (city, state_id) VALUES
    ('USAF Academy', (SELECT id FROM states WHERE abbreviation = 'CO')),
    ('Akron', (SELECT id FROM states WHERE abbreviation = 'OH')),
    ('Tuscaloosa', (SELECT id FROM states WHERE abbreviation = 'AL')),
    ('Boone', (SELECT id FROM states WHERE abbreviation = 'NC')),
    ('Tucson', (SELECT id FROM states WHERE abbreviation = 'AZ')),
    ('Tempe', (SELECT id FROM states WHERE abbreviation = 'AZ')),
    ('Fayetteville', (SELECT id FROM states WHERE abbreviation = 'AR')),
    ('Jonesboro', (SELECT id FROM states WHERE abbreviation = 'AR')),
    ('West Point', (SELECT id FROM states WHERE abbreviation = 'NY')),
    ('Auburn', (SELECT id FROM states WHERE abbreviation = 'AL')),
    ('Muncie', (SELECT id FROM states WHERE abbreviation = 'IN')),
    ('Waco', (SELECT id FROM states WHERE abbreviation = 'TX')),
    ('Boise', (SELECT id FROM states WHERE abbreviation = 'ID')),
    ('Chestnut Hill', (SELECT id FROM states WHERE abbreviation = 'MA')),
    ('Bowling Green', (SELECT id FROM states WHERE abbreviation = 'OH')),
    ('Buffalo', (SELECT id FROM states WHERE abbreviation = 'NY')),
    ('Provo', (SELECT id FROM states WHERE abbreviation = 'UT')),
    ('Berkeley', (SELECT id FROM states WHERE abbreviation = 'CA')),
    ('Mount Pleasant', (SELECT id FROM states WHERE abbreviation = 'MI')),
    ('Charlotte', (SELECT id FROM states WHERE abbreviation = 'NC')),
    ('Cincinnati', (SELECT id FROM states WHERE abbreviation = 'OH')),
    ('Clemson', (SELECT id FROM states WHERE abbreviation = 'SC')),
    ('Conway', (SELECT id FROM states WHERE abbreviation = 'SC')),
    ('Boulder', (SELECT id FROM states WHERE abbreviation = 'CO')),
    ('Fort Collins', (SELECT id FROM states WHERE abbreviation = 'CO')),
    ('Newark', (SELECT id FROM states WHERE abbreviation = 'DE')),
    ('Durham', (SELECT id FROM states WHERE abbreviation = 'NC')),
    ('Greenville', (SELECT id FROM states WHERE abbreviation = 'NC')),
    ('Ypsilanti', (SELECT id FROM states WHERE abbreviation = 'MI')),
    ('Boca Raton', (SELECT id FROM states WHERE abbreviation = 'FL')),
    ('Miami', (SELECT id FROM states WHERE abbreviation = 'FL')),
    ('Gainesville', (SELECT id FROM states WHERE abbreviation = 'FL')),
    ('Tallahassee', (SELECT id FROM states WHERE abbreviation = 'FL')),
    ('Fresno', (SELECT id FROM states WHERE abbreviation = 'CA')),
    ('Athens', (SELECT id FROM states WHERE abbreviation = 'GA')),
    ('Statesboro', (SELECT id FROM states WHERE abbreviation = 'GA')),
    ('Atlanta', (SELECT id FROM states WHERE abbreviation = 'GA')), -- Georgia State & Georgia Tech
    ('Honolulu', (SELECT id FROM states WHERE abbreviation = 'HI')),
    ('Houston', (SELECT id FROM states WHERE abbreviation = 'TX')), -- Houston & Rice
    ('Urbana-Champaign', (SELECT id FROM states WHERE abbreviation = 'IL')),
    ('Bloomington', (SELECT id FROM states WHERE abbreviation = 'IN')),
    ('Iowa City', (SELECT id FROM states WHERE abbreviation = 'IA')),
    ('Ames', (SELECT id FROM states WHERE abbreviation = 'IA')),
    ('Jacksonville', (SELECT id FROM states WHERE abbreviation = 'AL')),
    ('Harrisonburg', (SELECT id FROM states WHERE abbreviation = 'VA')),
    ('Lawrence', (SELECT id FROM states WHERE abbreviation = 'KS')),
    ('Manhattan', (SELECT id FROM states WHERE abbreviation = 'KS')),
    ('Kennesaw', (SELECT id FROM states WHERE abbreviation = 'GA')),
    ('Kent', (SELECT id FROM states WHERE abbreviation = 'OH')),
    ('Lexington', (SELECT id FROM states WHERE abbreviation = 'KY')),
    ('Lynchburg', (SELECT id FROM states WHERE abbreviation = 'VA')),
    ('Lafayette', (SELECT id FROM states WHERE abbreviation = 'LA')),
    ('Ruston', (SELECT id FROM states WHERE abbreviation = 'LA')),
    ('Louisville', (SELECT id FROM states WHERE abbreviation = 'KY')),
    ('Baton Rouge', (SELECT id FROM states WHERE abbreviation = 'LA')),
    ('Huntington', (SELECT id FROM states WHERE abbreviation = 'WV')),
    ('College Park', (SELECT id FROM states WHERE abbreviation = 'MD')),
    ('Memphis', (SELECT id FROM states WHERE abbreviation = 'TN')),
    ('Coral Gables', (SELECT id FROM states WHERE abbreviation = 'FL')),
    ('Oxford', (SELECT id FROM states WHERE abbreviation = 'OH')),
    ('Ann Arbor', (SELECT id FROM states WHERE abbreviation = 'MI')),
    ('East Lansing', (SELECT id FROM states WHERE abbreviation = 'MI')),
    ('Murfreesboro', (SELECT id FROM states WHERE abbreviation = 'TN')),
    ('Minneapolis', (SELECT id FROM states WHERE abbreviation = 'MN')),
    ('Starkville', (SELECT id FROM states WHERE abbreviation = 'MS')),
    ('Columbia', (SELECT id FROM states WHERE abbreviation = 'MO')),
    ('Springfield', (SELECT id FROM states WHERE abbreviation = 'MO')),
    ('Annapolis', (SELECT id FROM states WHERE abbreviation = 'MD')),
    ('Raleigh', (SELECT id FROM states WHERE abbreviation = 'NC')),
    ('Lincoln', (SELECT id FROM states WHERE abbreviation = 'NE')),
    ('Reno', (SELECT id FROM states WHERE abbreviation = 'NV')),
    ('Albuquerque', (SELECT id FROM states WHERE abbreviation = 'NM')),
    ('Las Cruces', (SELECT id FROM states WHERE abbreviation = 'NM')),
    ('Chapel Hill', (SELECT id FROM states WHERE abbreviation = 'NC')),
    ('Denton', (SELECT id FROM states WHERE abbreviation = 'TX')),
    ('DeKalb', (SELECT id FROM states WHERE abbreviation = 'IL')),
    ('Evanston', (SELECT id FROM states WHERE abbreviation = 'IL')),
    ('South Bend', (SELECT id FROM states WHERE abbreviation = 'IN')),
    ('Athens', (SELECT id FROM states WHERE abbreviation = 'OH')),
    ('Columbus', (SELECT id FROM states WHERE abbreviation = 'OH')),
    ('Norman', (SELECT id FROM states WHERE abbreviation = 'OK')),
    ('Stillwater', (SELECT id FROM states WHERE abbreviation = 'OK')),
    ('Norfolk', (SELECT id FROM states WHERE abbreviation = 'VA')),
    ('Oxford', (SELECT id FROM states WHERE abbreviation = 'MS')),
    ('Eugene', (SELECT id FROM states WHERE abbreviation = 'OR')),
    ('Corvallis', (SELECT id FROM states WHERE abbreviation = 'OR')),
    ('University Park', (SELECT id FROM states WHERE abbreviation = 'PA')),
    ('Pittsburgh', (SELECT id FROM states WHERE abbreviation = 'PA')),
    ('West Lafayette', (SELECT id FROM states WHERE abbreviation = 'IN')),
    ('Piscataway', (SELECT id FROM states WHERE abbreviation = 'NJ')),
    ('Huntsville', (SELECT id FROM states WHERE abbreviation = 'TX')),
    ('San Diego', (SELECT id FROM states WHERE abbreviation = 'CA')),
    ('San Jose', (SELECT id FROM states WHERE abbreviation = 'CA')),
    ('University Park', (SELECT id FROM states WHERE abbreviation = 'TX')),
    ('Mobile', (SELECT id FROM states WHERE abbreviation = 'AL')),
    ('Columbia', (SELECT id FROM states WHERE abbreviation = 'SC')),
    ('Tampa', (SELECT id FROM states WHERE abbreviation = 'FL')),
    ('Hattiesburg', (SELECT id FROM states WHERE abbreviation = 'MS')),
    ('Stanford', (SELECT id FROM states WHERE abbreviation = 'CA')),
    ('Syracuse', (SELECT id FROM states WHERE abbreviation = 'NY')),
    ('Fort Worth', (SELECT id FROM states WHERE abbreviation = 'TX')),
    ('Philadelphia', (SELECT id FROM states WHERE abbreviation = 'PA')),
    ('Knoxville', (SELECT id FROM states WHERE abbreviation = 'TN')),
    ('Austin', (SELECT id FROM states WHERE abbreviation = 'TX')),
    ('College Station', (SELECT id FROM states WHERE abbreviation = 'TX')),
    ('San Marcos', (SELECT id FROM states WHERE abbreviation = 'TX')),
    ('Lubbock', (SELECT id FROM states WHERE abbreviation = 'TX')),
    ('Toledo', (SELECT id FROM states WHERE abbreviation = 'OH')),
    ('Troy', (SELECT id FROM states WHERE abbreviation = 'AL')),
    ('New Orleans', (SELECT id FROM states WHERE abbreviation = 'LA')),
    ('Tulsa', (SELECT id FROM states WHERE abbreviation = 'OK')),
    ('Birmingham', (SELECT id FROM states WHERE abbreviation = 'AL')),
    ('Orlando', (SELECT id FROM states WHERE abbreviation = 'FL')),
    ('Los Angeles', (SELECT id FROM states WHERE abbreviation = 'CA')), -- USC & UCLA
    ('Storrs', (SELECT id FROM states WHERE abbreviation = 'CT')),
    ('Monroe', (SELECT id FROM states WHERE abbreviation = 'LA')),
    ('Amherst', (SELECT id FROM states WHERE abbreviation = 'MA')),
    ('Las Vegas', (SELECT id FROM states WHERE abbreviation = 'NV')),
    ('Salt Lake City', (SELECT id FROM states WHERE abbreviation = 'UT')),
    ('Logan', (SELECT id FROM states WHERE abbreviation = 'UT')),
    ('El Paso', (SELECT id FROM states WHERE abbreviation = 'TX')),
    ('San Antonio', (SELECT id FROM states WHERE abbreviation = 'TX')),
    ('Nashville', (SELECT id FROM states WHERE abbreviation = 'TN')),
    ('Charlottesville', (SELECT id FROM states WHERE abbreviation = 'VA')),
    ('Blacksburg', (SELECT id FROM states WHERE abbreviation = 'VA')),
    ('Winston-Salem', (SELECT id FROM states WHERE abbreviation = 'NC')),
    ('Seattle', (SELECT id FROM states WHERE abbreviation = 'WA')),
    ('Pullman', (SELECT id FROM states WHERE abbreviation = 'WA')),
    ('Morgantown', (SELECT id FROM states WHERE abbreviation = 'WV')),
    ('Bowling Green', (SELECT id FROM states WHERE abbreviation = 'KY')),
    ('Kalamazoo', (SELECT id FROM states WHERE abbreviation = 'MI')),
    ('Madison', (SELECT id FROM states WHERE abbreviation = 'WI')),
    ('Laramie', (SELECT id FROM states WHERE abbreviation = 'WY'));

INSERT OR IGNORE INTO teams (
    id,
    school, 
    mascot, 
    abbreviation, 
    location_id, 
    conference_id, 
    division_id
    ) VALUES
    (
        1,
        'Air Force',
        'Falcons', 
        'AFA', 
        (SELECT id FROM locations WHERE city = 'USAF Academy' AND state_id = (SELECT id FROM states WHERE abbreviation = 'CO')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    ),
    (
        2,
        'Akron',
        'Zips',
        'AKR',
        (SELECT id FROM locations WHERE city = 'Akron' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OH')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        3,
        'Alabama',
        'Crimson Tide',
        'ALA',
        (SELECT id FROM locations WHERE city = 'Tuscaloosa' AND state_id = (SELECT id FROM states WHERE abbreviation = 'AL')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        127,
        'Appalachian State',
        'Mountaineers',
        'APP ST',
        (SELECT id FROM locations WHERE city = 'Boone' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NC')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'East' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        4,
        'Arizona',
        'Wildcats',
        'AZ',
        (SELECT id FROM locations WHERE city = 'Tucson' AND state_id = (SELECT id FROM states WHERE abbreviation = 'AZ')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        5,
        'Arizona State',
        'Sun Devils',
        'ASU',
        (SELECT id FROM locations WHERE city = 'Tempe' AND state_id = (SELECT id FROM states WHERE abbreviation = 'AZ')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        6,
        'Arkansas',
        'Razorbacks',
        'ARK',
        (SELECT id FROM locations WHERE city = 'Fayetteville' AND state_id = (SELECT id FROM states WHERE abbreviation = 'AR')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        7,
        'Arkansas State',
        'Red Wolves',
        'ASU',
        (SELECT id FROM locations WHERE city = 'Jonesboro' AND state_id = (SELECT id FROM states WHERE abbreviation = 'AR')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'West' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        8,
        'Army',
        'Black Knights',
        'ARMY',
        (SELECT id FROM locations WHERE city = 'West Point' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NY')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        9,
        'Auburn',
        'Tigers',
        'AUB',
        (SELECT id FROM locations WHERE city = 'Auburn' AND state_id = (SELECT id FROM states WHERE abbreviation = 'AL')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        10,
        'Ball State',
        'Cardinals',
        'BALL',
        (SELECT id FROM locations WHERE city = 'Muncie' AND state_id = (SELECT id FROM states WHERE abbreviation = 'IN')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        11,
        'Baylor',
        'Bears',
        'BU',
        (SELECT id FROM locations WHERE city = 'Waco' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        12,
        'Boise State',
        'Broncos',
        'BOIS',
        (SELECT id FROM locations WHERE city = 'Boise' AND state_id = (SELECT id FROM states WHERE abbreviation = 'ID')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    ),
    (
        13,
        'Boston College',
        'Eagles',
        'BC',
        (SELECT id FROM locations WHERE city = 'Chestnut Hill' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MA')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        14,
        'Bowling Green',
        'Falcons',
        'BGSU',
        (SELECT id FROM locations WHERE city = 'Bowling Green' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OH')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        15,
        'Buffalo',
        'Bulls',
        'UB',
        (SELECT id FROM locations WHERE city = 'Buffalo' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NY')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        16,
        'BYU',
        'Cougars',
        'BYU',
        (SELECT id FROM locations WHERE city = 'Provo' AND state_id = (SELECT id FROM states WHERE abbreviation = 'UT')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        17,
        'California',
        'Golden Bears',
        'CAL',
        (SELECT id FROM locations WHERE city = 'Berkeley' AND state_id = (SELECT id FROM states WHERE abbreviation = 'CA')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        18,
        'Central Michigan',
        'Chippewas',
        'CMU',
        (SELECT id FROM locations WHERE city = 'Mount Pleasant' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MI')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        128,
        'Charlotte',
        '49ers',
        'CHAR',
        (SELECT id FROM locations WHERE city = 'Charlotte' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NC')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        19,
        'Cincinnati',
        'Bearcats',
        'CIN',
        (SELECT id FROM locations WHERE city = 'Cincinnati' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OH')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        20,
        'Clemson',
        'Tigers',
        'CLEM',
        (SELECT id FROM locations WHERE city = 'Clemson' AND state_id = (SELECT id FROM states WHERE abbreviation = 'SC')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        129,
        'Coastal Carolina',
        'Chanticleers',
        'CCU',
        (SELECT id FROM locations WHERE city = 'Conway' AND state_id = (SELECT id FROM states WHERE abbreviation = 'SC')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'East' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        21,
        'Colorado',
        'Buffaloes',
        'COLO',
        (SELECT id FROM locations WHERE city = 'Boulder' AND state_id = (SELECT id FROM states WHERE abbreviation = 'CO')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        22,
        'Colorado State',
        'Rams',
        'CSU',
        (SELECT id FROM locations WHERE city = 'Fort Collins' AND state_id = (SELECT id FROM states WHERE abbreviation = 'CO')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    ),
    (
        136,
        'Delaware',
        'Blue Hens',
        'DEL',
        (SELECT id FROM locations WHERE city = 'Newark' AND state_id = (SELECT id FROM states WHERE abbreviation = 'DE')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        24,
        'Duke',
        'Blue Devils',
        'DUKE',
        (SELECT id FROM locations WHERE city = 'Durham' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NC')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        26,
        'East Carolina',
        'Pirates',
        'ECU',
        (SELECT id FROM locations WHERE city = 'Greenville' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NC')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        25,
        'Eastern Michigan',
        'Eagles',
        'EMU',
        (SELECT id FROM locations WHERE city = 'Ypsilanti' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MI')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        28,
        'Florida Atlantic',
        'Owls',
        'FAU',
        (SELECT id FROM locations WHERE city = 'Boca Raton' AND state_id = (SELECT id FROM states WHERE abbreviation = 'FL')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        27,
        'Florida International',
        'Panthers',
        'FIU',
        (SELECT id FROM locations WHERE city = 'Miami' AND state_id = (SELECT id FROM states WHERE abbreviation = 'FL')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        29,
        'Florida',
        'Gators',
        'UF',
        (SELECT id FROM locations WHERE city = 'Gainesville' AND state_id = (SELECT id FROM states WHERE abbreviation = 'FL')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        30,
        'Florida State',
        'Seminoles',
        'FSU',
        (SELECT id FROM locations WHERE city = 'Tallahassee' AND state_id = (SELECT id FROM states WHERE abbreviation = 'FL')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        31,
        'Fresno State',
        'Bulldogs',
        'FRES',
        (SELECT id FROM locations WHERE city = 'Fresno' AND state_id = (SELECT id FROM states WHERE abbreviation = 'CA')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    ),
    (
        32,
        'Georgia',
        'Bulldogs',
        'UGA',
        (SELECT id FROM locations WHERE city = 'Athens' AND state_id = (SELECT id FROM states WHERE abbreviation = 'GA')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        130,
        'Georgia Southern',
        'Eagles',
        'GASO',
        (SELECT id FROM locations WHERE city = 'Statesboro' AND state_id = (SELECT id FROM states WHERE abbreviation = 'GA')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'East' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        33,
        'Georgia State',
        'Panthers',
        'GAST',
        (SELECT id FROM locations WHERE city = 'Atlanta' AND state_id = (SELECT id FROM states WHERE abbreviation = 'GA')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'East' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        34,
        'Georgia Tech',
        'Yellow Jackets',
        'GT',
        (SELECT id FROM locations WHERE city = 'Atlanta' AND state_id = (SELECT id FROM states WHERE abbreviation = 'GA')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        35,
        'Hawai''i',
        'Rainbow Warriors',
        'HAW',
        (SELECT id FROM locations WHERE city = 'Honolulu' AND state_id = (SELECT id FROM states WHERE abbreviation = 'HI')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    ),
    (
        36,
        'Houston',
        'Cougars',
        'HOU',
        (SELECT id FROM locations WHERE city = 'Houston' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        37,
        'Illinois',
        'Fighting Illini',
        'ILL',
        (SELECT id FROM locations WHERE city = 'Urbana-Champaign' AND state_id = (SELECT id FROM states WHERE abbreviation = 'IL')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        38,
        'Indiana',
        'Hoosiers',
        'IND',
        (SELECT id FROM locations WHERE city = 'Bloomington' AND state_id = (SELECT id FROM states WHERE abbreviation = 'IN')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        39,
        'Iowa',
        'Hawkeyes',
        'IOWA',
        (SELECT id FROM locations WHERE city = 'Iowa City' AND state_id = (SELECT id FROM states WHERE abbreviation = 'IA')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        40,
        'Iowa State',
        'Cyclones',
        'ISU',
        (SELECT id FROM locations WHERE city = 'Ames' AND state_id = (SELECT id FROM states WHERE abbreviation = 'IA')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        131,
        'Jacksonville State',
        'Gamecocks',
        'JSST',
        (SELECT id FROM locations WHERE city = 'Jacksonville' AND state_id = (SELECT id FROM states WHERE abbreviation = 'AL')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        132,
        'James Madison',
        'Dukes',
        'JMU',
        (SELECT id FROM locations WHERE city = 'Harrisonburg' AND state_id = (SELECT id FROM states WHERE abbreviation = 'VA')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'East' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        41,
        'Kansas',
        'Jayhawks',
        'KU',
        (SELECT id FROM locations WHERE city = 'Lawrence' AND state_id = (SELECT id FROM states WHERE abbreviation = 'KS')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        42,
        'Kansas State',
        'Wildcats',
        'KSU',
        (SELECT id FROM locations WHERE city = 'Manhattan' AND state_id = (SELECT id FROM states WHERE abbreviation = 'KS')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        43,
        'Kennesaw State',
        'Owls',
        'KENN',
        (SELECT id FROM locations WHERE city = 'Kennesaw' AND state_id = (SELECT id FROM states WHERE abbreviation = 'GA')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        44,
        'Kent State',
        'Golden Flashes',
        'KENT',
        (SELECT id FROM locations WHERE city = 'Kent' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OH')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        45,
        'Kentucky',
        'Wildcats',
        'UK',
        (SELECT id FROM locations WHERE city = 'Lexington' AND state_id = (SELECT id FROM states WHERE abbreviation = 'KY')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        133,
        'Liberty',
        'Flames',
        'LIB',
        (SELECT id FROM locations WHERE city = 'Lynchburg' AND state_id = (SELECT id FROM states WHERE abbreviation = 'VA')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        106,
        'Louisiana',
        'Ragin'' Cajuns',
        'UL',
        (SELECT id FROM locations WHERE city = 'Lafayette' AND state_id = (SELECT id FROM states WHERE abbreviation = 'LA')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'West' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        46,
        'Louisiana Tech',
        'Bulldogs',
        'LA TECH',
        (SELECT id FROM locations WHERE city = 'Ruston' AND state_id = (SELECT id FROM states WHERE abbreviation = 'LA')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        47,
        'Louisville',
        'Cardinals',
        'LOU',
        (SELECT id FROM locations WHERE city = 'Louisville' AND state_id = (SELECT id FROM states WHERE abbreviation = 'KY')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        48,
        'LSU',
        'Tigers',
        'LSU',
        (SELECT id FROM locations WHERE city = 'Baton Rouge' AND state_id = (SELECT id FROM states WHERE abbreviation = 'LA')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        49,
        'Marshall',
        'Thundering Herd',
        'MAR',
        (SELECT id FROM locations WHERE city = 'Huntington' AND state_id = (SELECT id FROM states WHERE abbreviation = 'WV')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'East' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        50,
        'Maryland',
        'Terrapins',
        'MD',
        (SELECT id FROM locations WHERE city = 'College Park' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MD')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        51,
        'Memphis',
        'Tigers',
        'MEM',
        (SELECT id FROM locations WHERE city = 'Memphis' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TN')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        52,
        'Miami',
        'Hurricanes',
        'MIA',
        (SELECT id FROM locations WHERE city = 'Miami' AND state_id = (SELECT id FROM states WHERE abbreviation = 'FL')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        53,
        'Miami (OH)',
        'RedHawks',
        'M-OH',
        (SELECT id FROM locations WHERE city = 'Oxford' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OH')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        54,
        'Michigan',
        'Wolverines',
        'MICH',
        (SELECT id FROM locations WHERE city = 'Ann Arbor' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MI')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        55,
        'Michigan State',
        'Spartans',
        'MSU',
        (SELECT id FROM locations WHERE city = 'East Lansing' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MI')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        56,
        'Middle Tennessee State',
        'Blue Raiders',
        'MTSU',
        (SELECT id FROM locations WHERE city = 'Murfreesboro' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TN')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        57,
        'Minnesota',
        'Golden Gophers',
        'MINN',
        (SELECT id FROM locations WHERE city = 'Minneapolis' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MN')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        58,
        'Mississippi State',
        'Bulldogs',
        'MSU',
        (SELECT id FROM locations WHERE city = 'Starkville' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MS')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        59,
        'Missouri',
        'Tigers',
        'MIZZ',
        (SELECT id FROM locations WHERE city = 'Columbia' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MO')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        135,
        'Missouri State',
        'Bears',
        'MOST',
        (SELECT id FROM locations WHERE city = 'Springfield' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MO')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        60,
        'Navy',
        'Midshipmen',
        'NAVY',
        (SELECT id FROM locations WHERE city = 'Annapolis' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MD')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        61,
        'NC State',
        'Wolfpack',
        'NCST',
        (SELECT id FROM locations WHERE city = 'Raleigh' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NC')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        62,
        'Nebraska',
        'Cornhuskers',
        'NEB',
        (SELECT id FROM locations WHERE city = 'Lincoln' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NE')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        63,
        'Nevada',
        'Wolf Pack',
        'NEV',
        (SELECT id FROM locations WHERE city = 'Reno' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NV')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    ),
    (
        64,
        'New Mexico',
        'Lobos',
        'UNM',
        (SELECT id FROM locations WHERE city = 'Albuquerque' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NM')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    ),
    (
        65,
        'New Mexico State',
        'Aggies',
        'NMSU',
        (SELECT id FROM locations WHERE city = 'Las Cruces' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NM')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        66,
        'North Carolina',
        'Tar Heels',
        'UNC',
        (SELECT id FROM locations WHERE city = 'Chapel Hill' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NC')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        67,
        'North Texas',
        'Mean Green',
        'UNT',
        (SELECT id FROM locations WHERE city = 'Denton' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        68,
        'Northern Illinois',
        'Huskies',
        'NIU',
        (SELECT id FROM locations WHERE city = 'DeKalb' AND state_id = (SELECT id FROM states WHERE abbreviation = 'IL')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        69,
        'Northwestern',
        'Wildcats',
        'NU',
        (SELECT id FROM locations WHERE city = 'Evanston' AND state_id = (SELECT id FROM states WHERE abbreviation = 'IL')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        70,
        'Notre Dame',
        'Fighting Irish',
        'ND',
        (SELECT id FROM locations WHERE city = 'South Bend' AND state_id = (SELECT id FROM states WHERE abbreviation = 'IN')),
        (SELECT id FROM conferences WHERE abbreviation = 'IND'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'IND'))
    ),
    (
        71,
        'Ohio',
        'Bobcats',
        'OHIO',
        (SELECT id FROM locations WHERE city = 'Athens' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OH')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        72,
        'Ohio State',
        'Buckeyes',
        'OSU',
        (SELECT id FROM locations WHERE city = 'Columbus' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OH')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        73,
        'Oklahoma',
        'Sooners',
        'OU',
        (SELECT id FROM locations WHERE city = 'Norman' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OK')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        74,
        'Oklahoma State',
        'Cowboys',
        'OSU',
        (SELECT id FROM locations WHERE city = 'Stillwater' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OK')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        75,
        'Old Dominion',
        'Monarchs',
        'ODU',
        (SELECT id FROM locations WHERE city = 'Norfolk' AND state_id = (SELECT id FROM states WHERE abbreviation = 'VA')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'East' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        76,
        'Ole Miss',
        'Rebels',
        'OM',
        (SELECT id FROM locations WHERE city = 'Oxford' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MS')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        77,
        'Oregon',
        'Ducks',
        'ORE',
        (SELECT id FROM locations WHERE city = 'Eugene' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OR')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        78,
        'Oregon State',
        'Beavers',
        'OSU',
        (SELECT id FROM locations WHERE city = 'Corvallis' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OR')),
        (SELECT id FROM conferences WHERE abbreviation = 'P12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'P12'))
    ),
    (
        79,
        'Penn State',
        'Nittany Lions',
        'PSU',
        (SELECT id FROM locations WHERE city = 'University Park' AND state_id = (SELECT id FROM states WHERE abbreviation = 'PA')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        80,
        'Pittsburgh',
        'Panthers',
        'PITT',
        (SELECT id FROM locations WHERE city = 'Pittsburgh' AND state_id = (SELECT id FROM states WHERE abbreviation = 'PA')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        81,
        'Purdue',
        'Boilermakers',
        'PUR',
        (SELECT id FROM locations WHERE city = 'West Lafayette' AND state_id = (SELECT id FROM states WHERE abbreviation = 'IN')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        82,
        'Rice',
        'Owls',
        'RICE',
        (SELECT id FROM locations WHERE city = 'Houston' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        83,
        'Rutgers',
        'Scarlet Knights',
        'RUTG',
        (SELECT id FROM locations WHERE city = 'Piscataway' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NJ')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        134,
        'Sam Houston',
        'Bearkats',
        'SHSU',
        (SELECT id FROM locations WHERE city = 'Huntsville' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        84,
        'San Diego State',
        'Aztecs',
        'SDSU',
        (SELECT id FROM locations WHERE city = 'San Diego' AND state_id = (SELECT id FROM states WHERE abbreviation = 'CA')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    ),
    (
        85,
        'San Jose State',
        'Spartans',
        'SJSU',
        (SELECT id FROM locations WHERE city = 'San Jose' AND state_id = (SELECT id FROM states WHERE abbreviation = 'CA')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    ),
    (
        86,
        'SMU',
        'Mustangs',
        'SMU',
        (SELECT id FROM locations WHERE city = 'University Park' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        87,
        'South Alabama',
        'Jaguar',
        'USA',
        (SELECT id FROM locations WHERE city = 'Mobile' AND state_id = (SELECT id FROM states WHERE abbreviation = 'AL')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'West' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        88,
        'South Carolina',
        'Gamecocks',
        'SC',
        (SELECT id FROM locations WHERE city = 'Columbia' AND state_id = (SELECT id FROM states WHERE abbreviation = 'SC')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        89,
        'Southern Miss',
        'Golden Eagles',
        'SO MISS',
        (SELECT id FROM locations WHERE city = 'Hattiesburg' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MS')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'West' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        90,
        'Stanford',
        'Cardinal',
        'STAN',
        (SELECT id FROM locations WHERE city = 'Stanford' AND state_id = (SELECT id FROM states WHERE abbreviation = 'CA')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        91,
        'Syracuse',
        'Orange',
        'SYR',
        (SELECT id FROM locations WHERE city = 'Syracuse' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NY')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        92,
        'TCU',
        'Horned Frogs',
        'TCU',
        (SELECT id FROM locations WHERE city = 'Fort Worth' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        93,
        'Temple',
        'Owls',
        'TEM',
        (SELECT id FROM locations WHERE city = 'Philadelphia' AND state_id = (SELECT id FROM states WHERE abbreviation = 'PA')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        94,
        'Tennessee',
        'Volunteers',
        'TEN',
        (SELECT id FROM locations WHERE city = 'Knoxville' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TN')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        96,
        'Texas',
        'Longhorns',
        'TEX',
        (SELECT id FROM locations WHERE city = 'Austin' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        95,
        'Texas A&M',
        'Aggies',
        'TAMU',
        (SELECT id FROM locations WHERE city = 'College Station' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        97,
        'Texas State',
        'Bobcats',
        'TXST',
        (SELECT id FROM locations WHERE city = 'San Marcos' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'West' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        98,
        'Texas Tech',
        'Red Raiders',
        'TTU',
        (SELECT id FROM locations WHERE city = 'Lubbock' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        99,
        'Toledo',
        'Rockets',
        'TOL',
        (SELECT id FROM locations WHERE city = 'Toledo' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OH')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        100,
        'Troy',
        'Trojans',
        'TROY',
        (SELECT id FROM locations WHERE city = 'Troy' AND state_id = (SELECT id FROM states WHERE abbreviation = 'AL')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'West' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        101,
        'Tulane',
        'Green Wave',
        'TUL',
        (SELECT id FROM locations WHERE city = 'New Orleans' AND state_id = (SELECT id FROM states WHERE abbreviation = 'LA')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        102,
        'Tulsa',
        'Golden Hurricane',
        'TUL',
        (SELECT id FROM locations WHERE city = 'Tulsa' AND state_id = (SELECT id FROM states WHERE abbreviation = 'OK')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        103,
        'UAB',
        'Blazers',
        'UAB',
        (SELECT id FROM locations WHERE city = 'Birmingham' AND state_id = (SELECT id FROM states WHERE abbreviation = 'AL')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        104,
        'UCF',
        'Knights',
        'UCF',
        (SELECT id FROM locations WHERE city = 'Orlando' AND state_id = (SELECT id FROM states WHERE abbreviation = 'FL')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        105,
        'UCLA',
        'Bruins',
        'UCLA',
        (SELECT id FROM locations WHERE city = 'Los Angeles' AND state_id = (SELECT id FROM states WHERE abbreviation = 'CA')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        23,
        'UConn',
        'Huskies',
        'UCONN',
        (SELECT id FROM locations WHERE city = 'Storrs' AND state_id = (SELECT id FROM states WHERE abbreviation = 'CT')),
        (SELECT id FROM conferences WHERE abbreviation = 'IND'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'IND'))
    ),
    (
        107,
        'ULM',
        'Warhawks',
        'ULM',
        (SELECT id FROM locations WHERE city = 'Monroe' AND state_id = (SELECT id FROM states WHERE abbreviation = 'LA')),
        (SELECT id FROM conferences WHERE abbreviation = 'SBC'),
        (SELECT id FROM divisions WHERE name IS 'West' AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SBC'))
    ),
    (
        108,
        'UMass',
        'Minutemen',
        'UMASS',
        (SELECT id FROM locations WHERE city = 'Amherst' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MA')),
        (SELECT id FROM conferences WHERE abbreviation = 'IND'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'IND'))
    ),
    (
        109,
        'UNLV',
        'Runnin'' Rebels',
        'UNLV',
        (SELECT id FROM locations WHERE city = 'Las Vegas' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NV')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    ),
    (
        110,
        'USC',
        'Trojans',
        'USC',
        (SELECT id FROM locations WHERE city = 'Los Angeles' AND state_id = (SELECT id FROM states WHERE abbreviation = 'CA')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        111,
        'USF',
        'Bulls',
        'USF',
        (SELECT id FROM locations WHERE city = 'Tampa' AND state_id = (SELECT id FROM states WHERE abbreviation = 'FL')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        112,
        'Utah',
        'Utes',
        'UTAH',
        (SELECT id FROM locations WHERE city = 'Salt Lake City' AND state_id = (SELECT id FROM states WHERE abbreviation = 'UT')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        113,
        'Utah State',
        'Aggies',
        'USU',
        (SELECT id FROM locations WHERE city = 'Logan' AND state_id = (SELECT id FROM states WHERE abbreviation = 'UT')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    ),
    (
        114,
        'UTEP',
        'Miners',
        'UTEP',
        (SELECT id FROM locations WHERE city = 'El Paso' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        115,
        'UTSA',
        'Roadrunners',
        'UTSA',
        (SELECT id FROM locations WHERE city = 'San Antonio' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TX')),
        (SELECT id FROM conferences WHERE abbreviation = 'AAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'AAC'))
    ),
    (
        116,
        'Vanderbilt',
        'Commodores',
        'VAND',
        (SELECT id FROM locations WHERE city = 'Nashville' AND state_id = (SELECT id FROM states WHERE abbreviation = 'TN')),
        (SELECT id FROM conferences WHERE abbreviation = 'SEC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'SEC'))
    ),
    (
        117,
        'Virginia',
        'Cavaliers',
        'UVA',
        (SELECT id FROM locations WHERE city = 'Charlottesville' AND state_id = (SELECT id FROM states WHERE abbreviation = 'VA')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        118,
        'Virginia Tech',
        'Hokies',
        'VT',
        (SELECT id FROM locations WHERE city = 'Blacksburg' AND state_id = (SELECT id FROM states WHERE abbreviation = 'VA')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        119,
        'Wake Forest',
        'Demon Deacons',
        'WF',
        (SELECT id FROM locations WHERE city = 'Winston-Salem' AND state_id = (SELECT id FROM states WHERE abbreviation = 'NC')),
        (SELECT id FROM conferences WHERE abbreviation = 'ACC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'ACC'))
    ),
    (
        120,
        'Washington',
        'Huskies',
        'UW',
        (SELECT id FROM locations WHERE city = 'Seattle' AND state_id = (SELECT id FROM states WHERE abbreviation = 'WA')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        121,
        'Washington State',
        'Cougars',
        'WSU',
        (SELECT id FROM locations WHERE city = 'Pullman' AND state_id = (SELECT id FROM states WHERE abbreviation = 'WA')),
        (SELECT id FROM conferences WHERE abbreviation = 'P12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'P12'))
    ),
    (
        122,
        'West Virginia',
        'Mountaineers',
        'WVU',
        (SELECT id FROM locations WHERE city = 'Morgantown' AND state_id = (SELECT id FROM states WHERE abbreviation = 'WV')),
        (SELECT id FROM conferences WHERE abbreviation = 'B12'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B12'))
    ),
    (
        123,
        'Western Kentucky',
        'Hilltoppers',
        'WKU',
        (SELECT id FROM locations WHERE city = 'Bowling Green' AND state_id = (SELECT id FROM states WHERE abbreviation = 'KY')),
        (SELECT id FROM conferences WHERE abbreviation = 'CUSA'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'CUSA'))
    ),
    (
        124,
        'Western Michigan',
        'Broncos',
        'WMU',
        (SELECT id FROM locations WHERE city = 'Kalamazoo' AND state_id = (SELECT id FROM states WHERE abbreviation = 'MI')),
        (SELECT id FROM conferences WHERE abbreviation = 'MAC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MAC'))
    ),
    (
        125,
        'Wisconsin',
        'Badgers',
        'WIS',
        (SELECT id FROM locations WHERE city = 'Madison' AND state_id = (SELECT id FROM states WHERE abbreviation = 'WI')),
        (SELECT id FROM conferences WHERE abbreviation = 'B10'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'B10'))
    ),
    (
        126,
        'Wyoming',
        'Cowboys',
        'WYO',
        (SELECT id FROM locations WHERE city = 'Laramie' AND state_id = (SELECT id FROM states WHERE abbreviation = 'WY')),
        (SELECT id FROM conferences WHERE abbreviation = 'MWC'),
        (SELECT id FROM divisions WHERE name IS NULL AND conference_id = (SELECT id FROM conferences WHERE abbreviation = 'MWC'))
    );

